spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  jpa:
    database: postgresql
  datasource:
    username: docker
    password: docker
    url: '@jdbc.url@'
server:
  port: 8082
#  ssl:
#    key-alias: smarthouse
#    key-store-password: passwd
#    key-store: classpath:h2sm.p12
#    key-store-type: PKCS12
#    enabled: true
h2sm:
  app:
    jwtSecret: NETVOYNENETVOYNENETVOYNENETVOYNENETVOYNENETVOYNE
    jwtExpirationMs: 360000000

