spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  jpa:
    database: postgresql
    show-sql: false
  datasource:
    username: docker
    password: docker
    url: '@jdbc.url@'
    driver-class-name: org.postgresql.Driver
server:
  port: 8082
#  ssl:
#    key-alias: smarthouse
#    key-store-password: passwd
#    key-store: classpath:h2sm.p12
#    key-store-type: PKCS12
#    enabled: true
h2sm:
  app:
    jwtSecret: BARABARABARABEREBEREBEREBARABARABARABEREBEREBERE
    jwtExpirationMs: 360000000

db:
  driver: org.postgresql.Driver
  url: '@jdbc.url@'
  username: docker
  password: docker