spring:
  jpa:
    database: postgresql
  datasource:
    username: docker
    password: docker
    url: jdbc:postgresql://localhost:5432/SmarthomeDB
server:
  port: 8082

h2sm:
  app:
    jwtSecret: NETVOYNENETVOYNENETVOYNENETVOYNENETVOYNENETVOYNE
    jwtExpirationMs: 86400000
